# Generated by Django 3.1.3 on 2021-01-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0002_customuser_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='experience',
            field=models.CharField(blank=True, choices=[('JUNIOR', 'Junior Developer'), ('MIDDLE', 'Middle Developer'), ('SENIOR', 'Senior Developer')], default='JUNIOR', max_length=100, null=True, verbose_name='experience'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='description'),
        ),
    ]
