# Generated by Django 3.1.3 on 2021-01-23 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0005_auto_20210107_2228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
