# Generated by Django 3.1.3 on 2020-12-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0006_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='snippets', to='snippet.Tag'),
        ),
    ]
